/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLSimulationModel.Nacelle.Generator;

import GEWindTurbineSysMLSimulationModel.RotorHub.Rotor;
import GEWindTurbineSysMLSimulationModel.Tower.Transformer;

/************************************************************/
/**
 * 
 */
public class Alternator {
	/**
	 * 
	 */
	public Rotor rotorFromWhichItAdaptsItsOwnRotation;
	/**
	 * 
	 */
	public Transformer transformerForThePowerGeneration;
}
