/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLSimulationModel.RotorHub;

/************************************************************/
/**
 * 
 */
public class Rotor {
	/**
	 * 
	 */
	public void rotate() {
	}
}
