/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLStructuralModel.NacelleModel.GeneratorModel;

import GEWindTurbineSysMLStructuralModel.RotorHubModel.Rotor;
import GEWindTurbineSysMLStructuralModel.TowerModel.Transformer;

/************************************************************/
/**
 * 
 */
public class Alternator {
	/**
	 * 
	 */
	public Rotor rotorFromWhichItAdaptsItsOwnRotation;
	/**
	 * 
	 */
	public Transformer transformerForThePowerGeneration;
}
