/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLSimulationModel.Tower;

/************************************************************/
/**
 * 
 */
public class Transformer {
}
