/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class Alternator {
	/**
	 * 
	 */
	public Rotor rotorFromWhichItAdaptasItsOwnRotation;
	/**
	 * 
	 */
	public Transformer transformerForTheEnergyGeneration;

	/**
	 * 
	 */
	public void generateEnergy() {
	}

	/**
	 * 
	 */
	public void adaptsRotation() {
	}
}
