/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class Generator {
	/**
	 * 
	 */
	public Alternator alternator;
}
