// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class Generator {
	/**
	 * 
	 */
	public Alternator alternator;
}
