// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class ManualBrakingSystem {
}
