// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class Nacelle {
	/**
	 * 
	 */
	public Multiplier multiplier;
	/**
	 * 
	 */
	public Generator generator;
	/**
	 * 
	 */
	public ManualBrakingSystem brake;
}
