/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class Nacelle {
	/**
	 * 
	 */
	public Multiplier multiplier;
	/**
	 * 
	 */
	public Generator generator;
	/**
	 * 
	 */
	public ManualBrakingSystem brake;
}
