/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class RotorHub {
	/**
	 * 
	 */
	public Rotor rotor;
}
