// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class RotorHub {
	/**
	 * 
	 */
	public Rotor rotor;
}
