// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class Tower {
	/**
	 * 
	 */
	public OrientationSystem orientationSystem;
}
