/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class WindTurbine {
	/**
	 * 
	 */
	public RotorHub rotorhub;
	/**
	 * 
	 */
	public Fondation fondation;
	/**
	 * 
	 */
	public Tower tower;
	/**
	 * 
	 */
	public Transformer transformer;
	/**
	 * 
	 */
	public Nacelle nacelle;
	/**
	 * 
	 */
	public Blade[] blades;
}
