// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GEWindTurbineUMLDomainModel;

/************************************************************/
/**
 * 
 */
public class WindTurbine {
	/**
	 * 
	 */
	public RotorHub rotorhub;
	/**
	 * 
	 */
	public Fondation fondation;
	/**
	 * 
	 */
	public Tower tower;
	/**
	 * 
	 */
	public Transformer transformer;
	/**
	 * 
	 */
	public Nacelle nacelle;
	/**
	 * 
	 */
	public Blade blade;
}
