/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLSimulationModel.Nacelle;

/************************************************************/
/**
 * 
 */
public class ManualBrake {
}
