/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLSimulationModel.Nacelle;

import GEWindTurbineSysMLSimulationModel.Nacelle.Generator.Generator;

/************************************************************/
/**
 * 
 */
public class Nacelle {
	/**
	 * 
	 */
	public Generator generator;
	/**
	 * 
	 */
	public ManualBrake manualbrake;
	/**
	 * 
	 */
	public Multiplier multiplier;
}
