/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLStructuralModel.NacelleModel;

/************************************************************/
/**
 * 
 */
public class ManualBrake {
}
