/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLStructuralModel.NacelleModel;

import GEWindTurbineSysMLStructuralModel.NacelleModel.GeneratorModel.Generator;

/************************************************************/
/**
 * 
 */
public class Nacelle {
	/**
	 * 
	 */
	public Generator generator;
	/**
	 * 
	 */
	public ManualBrake manualbrake;
	/**
	 * 
	 */
	public Multiplier multiplier;
}
