/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLStructuralModel.TowerModel;

/************************************************************/
/**
 * 
 */
public class Transformer {
}
