/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLSimulationModel;

/************************************************************/
/**
 * 
 */
public class AlternatorPowerGeneration {
}
