/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLStructuralModel;

/************************************************************/
/**
 * 
 */
public class MaintenanceDB {
}
