/**
* @author Rindra Mbolamananamalala
* Automatically generated by Papyrus Java Code generator
*/
package GEWindTurbineSysMLStructuralModel;

import GEWindTurbineSysMLStructuralModel.NacelleModel.Nacelle;
import GEWindTurbineSysMLStructuralModel.RotorHubModel.RotorHub;
import GEWindTurbineSysMLStructuralModel.TowerModel.Tower;

/************************************************************/
/**
 * 
 */
public class WindTurbine {
	/**
	 * 
	 */
	public Nacelle nacelle;
	/**
	 * 
	 */
	public RotorHub rotorHub;
	/**
	 * 
	 */
	public Tower tower;
}
